import { test, expect } from '@playwright/test';

test('desactivar etiquetas "editable"', async ({ page }) => {
  await page.goto('https://demos.staging.khor.mx/');
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).click();
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).fill('pato1');
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Password123*');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('button', { name: 'code-sandbox-circle AAA down' }).click();
  await page.getByText('WorkBecarios').click();
  await page.getByRole('img', { name: 'cover' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Configuración$/ }).nth(1).click();
  await page.getByText('Etiquetas del sistem...').click();
  await page.getByRole('switch').nth(4).click();
  await page.locator('div:nth-child(3) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(4) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(5) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(6) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(7) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(8) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(9) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(10) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(11) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(12) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(13) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(14) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(15) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(16) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(17) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(18) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(19) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(20) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(21) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(22) > div:nth-child(7) > span > .ant-switch').first().click();
  await page.locator('div:nth-child(23) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(24) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(25) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(26) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(27) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(28) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(29) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(30) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(31) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(32) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(34) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(35) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(36) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(37) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(38) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(39) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(40) > div:nth-child(7) > span > .ant-switch').click();
  await page.locator('div:nth-child(41) > div:nth-child(7) > span > .ant-switch').click();
  await page.getByRole('img', { name: 'user' }).locator('svg').click();
  await page.getByText('Cerrar sesión').click();
  await page.locator('span').nth(4).click();

  await page.getByRole('img', { name: 'user' }).locator('svg').click();
  await page.getByText('Cerrar sesión').click();
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).fill('patricio.escalante');
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Pato123456@');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('img', { name: 'cover' }).click();

  await page.locator('div').filter({ hasText: /^Personas$/ }).nth(1).click();
  await page.getByRole('menu').getByText('Personas').click();
  await page.locator('a').filter({ hasText: 'INT00003540' }).click();
  await page.waitForTimeout(3000);
  await expect(page.getByRole('textbox', { name: '* Nombre(s)' })).toBeDisabled();

  await expect(page.getByRole('combobox', { name: 'Tratamiento' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: '* Nombre(s)' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: '* Apellido paterno' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Apellido materno' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Área funcional' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Género' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Correo Electrónico' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'División' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Departamento' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Estado Civil' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha de Nacimiento' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'CURP' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'RFC' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'No. Seguro Social' })).toBeDisabled();
  await expect(page.getByRole('spinbutton', { name: 'Expectativa Económica' })).toBeDisabled();
  await expect(page.locator('#profile-expediente-focus-daily_salary')).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Mano Habil' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Acceso a Connect' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha de Ingreso a la Empresa' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha para Antigüedad' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha para de Ingreso al Grupo' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha de ingreso al país' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Referenciado' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Nacionalidad', exact: true })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'País' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Estado', exact: true })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Municipio' })).toBeDisabled();
  await expect(page.getByRole('combobox', { name: 'Tipo de Nacionalidad' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha de Naturalización' })).toBeDisabled();
  await expect(page.getByRole('switch', { name: 'Disponibilidad para Viajar' })).toBeDisabled();
  await expect(page.getByRole('switch', { name: 'Disponibilidad para Cambio de' })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'Fecha de Terminación Laboral' })).toBeDisabled();

  
});
