import { test, expect } from '@playwright/test';
test.setTimeout(60000);
test('test', async ({ page }) => {
  await page.goto('https://demos.staging.khor.mx/');
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).click();
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).fill('patricio.escalante');
  await page.getByRole('textbox', { name: 'Usuario info-circle' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Pato123456@');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).first().click();
  await page.getByRole('img', { name: 'cover' }).click();
  await page.locator('div:nth-child(3) > .ant-card-body > .anticon > svg').first().click();
  await page.getByRole('menu').getByText('Personas').click();
  await page.getByRole('button', { name: 'plus Agregar persona' }).click();
  await page.getByRole('textbox', { name: '* Nombre(s)' }).click();
  await page.getByRole('textbox', { name: '* Nombre(s)' }).fill('Genaroooo');
  await page.getByRole('textbox', { name: '* Nombre(s)' }).press('Tab');
  await page.getByRole('textbox', { name: '* Apellido paterno' }).fill('Medina');
  await page.waitForTimeout(1000);
  await page.getByRole('combobox', { name: '* Tipo de persona' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('Personal Interno (INT)').first().click();
  await page.getByRole('textbox', { name: '* Usuario' }).click();
  await page.getByRole('textbox', { name: '* Usuario' }).fill('genaro.medina4');
  await page.getByRole('textbox', { name: '* Código de empleado' }).click();
  await page.getByRole('textbox', { name: '* Código de empleado' }).fill('3539');
  await page.getByRole('textbox', { name: '* Contraseña' }).click();
  await page.getByRole('textbox', { name: '* Contraseña' }).fill('Password123*');
  await page.getByRole('textbox', { name: '* Confirmar contraseña' }).click();
  await page.getByRole('textbox', { name: '* Confirmar contraseña' }).fill('Password123*');
  await page.getByRole('button', { name: 'Guardar y regresar' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Buscar...' }).click();
  await page.getByRole('textbox', { name: 'Buscar...' }).fill('genaroooo');
  await page.getByRole('textbox', { name: 'Buscar...' }).press('Enter');
  await page.getByRole('cell', { name: 'INT00003539' }).locator('a').click();
  await page.waitForTimeout(1000);
  await page.getByRole('combobox', { name: 'Tratamiento' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('(Sr.) Señor').click();
  await page.getByRole('combobox', { name: 'Área funcional' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('(ABAS03) ABAST. (IMPORT. Y').click();
  await page.getByRole('combobox', { name: 'Género' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('Masculino').nth(1).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('genarooo.medina@gmail.com');
  /*await page.locator('#profile-expediente-focus-branch_id').click();
  await page.getByText('Sucursal 2').click();*/
  await page.getByRole('combobox', { name: 'División' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('División 1', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Selecciona una opción$/ }).nth(3).click();
  await page.getByText('Departamento 7').click();
  await page.getByRole('combobox', { name: 'Estado Civil' }).click();
  await page.waitForTimeout(1000);
  await page.getByText('Soltero(a)').click();
  await page.getByRole('textbox', { name: 'Fecha de Nacimiento' }).click();
  await page.getByRole('textbox', { name: 'Fecha de Nacimiento' }).fill('13/04/1999');
  await page.locator('.anticon.anticon-delivered-procedure > svg').first().click();
  await page.locator('.anticon.anticon-delivered-procedure.ant-tooltip-open > svg').click();
  await page.getByRole('spinbutton', { name: 'Expectativa Económica' }).click();
  await page.getByRole('spinbutton', { name: 'Expectativa Económica' }).fill('140000');
  await page.locator('#profile-expediente-focus-daily_salary').click();
  await page.locator('#profile-expediente-focus-daily_salary').fill('450');
  await page.getByRole('combobox', { name: 'País' }).fill('mex');
  await page.waitForTimeout(1000);
  await page.getByText('México').click();
  await page.getByRole('combobox', { name: 'Estado', exact: true }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('combobox', { name: 'Estado', exact: true }).fill('yuca');
  await page.waitForTimeout(1000);
  await page.getByText('Yucatán').click();
  await page.getByRole('combobox', { name: 'Municipio' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('combobox', { name: 'Municipio' }).fill('merida');
  await page.waitForTimeout(1000);
  await page.getByText('Mérida').click();
  await page.getByRole('switch', { name: 'Disponibilidad para Viajar' }).click();
  await page.getByRole('switch', { name: 'Disponibilidad para Cambio de' }).click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.waitForTimeout(2000);

});